### ISSUE TITLE
syntax error: unexpected 'newline'

### ISSUE THREAD

**Issue by rushkii** [httptoolkit/frida-android-unpinning#33]
Running command returning syntax error.
```sh
> adb shell "/data/local/tmp/frida-server &"
/data/local/tmp/frida-server[1]: syntax error: unexpected 'newline'
```

**Comment by pimterry** [comment]
This must be an issue with your Frida setup, not with this script. I'm not sure what that `frida-server` file contains in your case, but it's not the normal Frida server binary - that error suggests it's being treated as a script or similar. Maybe you've accidentally downloaded an error page instead, or you've pushed the wrong file? You can download and extract Frida from here: https://github.com/frida/frida/releases/.

I'm going to close this, since it's not related to this repo. If you're having issues with running Frida server in the first place, you should open an issue with Frida itself, they should be able to help you out.

**Comment by pimterry** [comment]
Frida-core-devkit is not correct - you want frida-server

**Comment by rushkii** [comment]
> Frida-core-devkit is not correct - you want frida-server

Ahh, I see. I downloaded the wrong release version, previous one has android frida server, thank you.
