### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by 89z** [httptoolkit/frida-android-unpinning#8]
If I try to use `frida-script.js` with this app:

~~~
com.vimeo.android.videoapp
~~~

and I start the app, it prompts for login. Alternatively you can hit SKIP in the top right corner. If I hit SKIP, I get this message:

~~~
Something strange occurred
Sorry about that. Please try again.
~~~

If I try again, same error. If I then disable proxy and try again, it works.

**Comment by 89z** [comment]
workaround:

https://github.com/WooyunDota/DroidSSLUnpinning/blob/master/ObjectionUnpinningPlus/hooks.js

**Comment by pimterry** [comment]
You linked a workaround, but that comment's now been deleted. Is that because the workaround didn't work? If it does work, it'd be really useful to check which specific pinning mechanism it's blocking, so we can do the same thing here.

If the workaround doesn't work, and you're still stuck, I'd suggest investigating https://github.com/vimeo/vimeo-networking-java - that's the official Vimeo SDK, which includes some certificate pinning features. If you can do a little digging to confirm that that is being used by their own app (seems likely) then it's probably worth exploring that library more closely, and adding a hook here to disable that pinning automatically.

**Comment by 89z** [comment]
If I remember right, the option I thought was a workaround, only worked with proxy disabled. I tested a bunch of Frida scripts, and most of them didnt even work with proxy disabled. The workaround (and the script here) work with proxy disabled, but thats kind of pointless. Proxy needs to be enabled, so traffic can be viewed.

The only other option I thought of, was a Frida script that just logs all network requests. That way, you wouldnt need a proxy. Have you thought about something like that?

**Comment by pimterry** [comment]
That is very possible, but it has its own challenges. You would need to hook every single way of sending HTTP requests, in the same way that you currently need to hook every way of pinning certificates (and I think there are many more HTTP clients than certificate validation libraries, and each one has a much more complicated API). You could try to do it at the TLS socket level, but that has similar problems, and then you're getting totally raw streams of data, which is harder to work with than already structured requests & responses.

It'd also be _much_ harder to do anything beyond just viewing traffic there, like modifying individual requests in flight.

That's in terms of building general solutions though - to quickly hook up a script for a one-off case, it might well work for your needs.

Anyway, I've had a quick look at the Vimeo app, decompiling it with [ApkTool](https://ibotpeaches.github.io/Apktool/), and it clearly does use its own networking SDK that includes certificate pinning, so that's almost certainly the problem. I haven't investigated that in more depth, but if we can hunt down the relevant methods there it should be easy to disable them.

Do you want to take a look at that? I might be able to do it, but not for a few days at least I expect. If you work out where the certificate pinning is, you can probably add another hook (the script here is full of examples) and disable the method that enables it, or change a `checkCertificate(cert)` method to always return true or something. Does that make sense?

**Comment by 89z** [comment]
I found a solution here:

https://github.com/shroudedcode/apk-mitm/issues/34#issuecomment-770393173

that I can confirm does fix the problem. However I would really like to avoid patching APKs, as its a painful process of decompiling APK, then searching some confusing SMALI code or whatever that is, then modifying and repackaging. Then, maybe all that doesnt even work for any other apps, but only one specific app. So in instead its possible to have something more general working with Frida, I would prefer that. But if a specific solution is required regardless, I think a Frida solution is better to a patching solution, as you can just use the source APK as is.

**Comment by pimterry** [comment]
Ok, yes that makes perfect sense.

The magic of Frida is that you don't have to patch APKs to do this same change - Frida allows you to write a quick script which can modify the application very easily at runtime.

I'm going to dig into this myself over the next few days. I've been meaning to write up a reverse engineering article, and maybe this will be a useful example! I'll let you know if I make any progress, watch this space.

**Comment by pimterry** [comment]
I'll write up the full article with background later, but for now I've got a working fix you might be interested in. Just add this into your Frida script:

```
Java.use('w.r').a.implementation = function () {
    console.log('w.r a called'); return;
}
```

Tested against Vimeo 3.51.0 from https://apkpure.com/vimeo/com.vimeo.android.videoapp - be aware that the obfuscated name might well change for different versions.

In short: the `a` method in the `w.r` class seems to be where certificate pinning is currently happening - this just blocks that so it never throws. If it's working, you should see the log message above appearing in your Frida output, and `api.vimeo.com` requests being proxied correctly. For me after that script is run everything works perfectly.

Unfortunately I can't add this permanently to the normal script, because in other obfuscated apps `w.r` might be a totally unrelated class. I'm not sure if there's a good way with Frida to match against the bytecode itself to handle this, but I'll have a quick look and see what I can do.

**Comment by 89z** [comment]
Yeah, the name definitely will change - I noticed that from January it had one name, then October another name. It might even change every version, not sure. Regardless, this is a great start. As I said before Frida script way better than patching APK! Great work, I will try to check it out today, and maybe see if I can find a more general fix!

**Comment by pimterry** [comment]
I've done something ridiculous that I think solves this for the general case, at least for all applications using this same version of OkHttp, regardless of obfuscation. Check this out: https://github.com/httptoolkit/frida-android-unpinning/commit/91422adeda7982e32d761e7efe6ac95286eb8254

**Comment by 89z** [comment]
Oh man... thats looks promising! So like in the case of Vimeo, I am guessing youd still get the initial `Something strange occurred`, but then if you tried it again, everything would be fine from then on? If thats the case great! If that is the case though, that makes me wonder, maybe other people fixed this already too? Im not certain that I tried two times with all the Frida scripts I tested. At any rate, this is very cool. I will try to look at this more today!

**Comment by pimterry** [comment]
Yep, you have to click 'Try again' for the very first request, but then it works nicely.

Alternatively, if you need it to run it perfectly from the start, you can use the logs from this script to do that too, since the output includes the exact class & method name that threw the error. With those it's easy to add a custom one-off hook to the script that disables that method immediately, with no reverse engineering required. Just add the below (using the class & method name from the logs) anywhere inside the `Java.perform` callback:

```js
// Replace pkg.pkg.the-class-name.theMethodName with a no-op function that returns Void:
Java.use("pkg.pkg.the-class-name").theMethodName.implementation = function () {
  return;
};
```

**Comment by 89z** [comment]
With the app as it currently is, the initial error is fine. If the app somehow made it, so that the initial error crashed the whole app, then it would be a problem. But since you can dismiss the initial error and try again, then I say the fix is good as is. I would only suggest that we try to make this clear, so that users know that the script works, but you just need to try again. Maybe something like this:

~~~js
console.log('  --> Unexpected SSL verification failure, adding dynamic patch. Try interaction again.');
~~~

probably could be worded better.

**Comment by pimterry** [comment]
Just FYI, I've written up some background on doing this kind of reverse engineering investigation for yourself that you might find interesting here: https://httptoolkit.tech/blog/android-reverse-engineering/.

I'm going to close this issue for now. I'm sure there's definitely more improvements possible (PRs welcome!) and I'll keep working on this script in various directions where I can, but I think there's enough here that you can use to get Vimeo working now.

**Comment by 89z** [comment]
Thanks very much for everything! I stepped away from working on this for a little bit, as I was getting frustrated with all the tactics these companies use, but I might try to look at it again today or tomorrow. Appreciate you sharing your detailed knowledge, some people online are smart, but they keep the information to themself, only sharing maybe some keys or end result. You sharing "how to do something" or "teach someone to fish", is an invaluable resource.
